// Words for the safety panel (UI brief section 4). Plain operator language.

export const SAFETY_COPY = {
  title: 'Safety',
  overallLabel: 'Overall safety',
  missingEvidence: 'Missing evidence',
  notValidated: 'Not from a validated assessment. These results are for demonstration and cannot be relied on.',
  familyChecksTitle: 'Family checks',
  noFamilyChecks: 'No checks returned for this family. Treat it as Unknown.',
  noConditions: 'No limiting condition confirmed yet, so no family checks apply.',
  crossChecksTitle: 'Other affected limits',
  crossChecksNote: 'An action can help one limit and use up another, such as battery headroom promised for frequency service.',
  noCrossChecks: 'No other affected limits returned.',
  allIslandTitle: 'All-island limits that affect this decision',
  noAllIslandChecks: 'No all-island checks returned. Treat them as Unknown.',
  actionChecksTitle: 'Action-specific checks',
  actionChecksNote: 'Action checks add to the family checks. They never replace them.',
  noPlan: 'No plan selected. Action checks appear once a plan is chosen.',
  noStepChecks: 'No action checks returned for this step. Treat it as Unknown.',
  goNoGo: 'Go/no-go',
  step: 'Step',
  notAvailable: 'Not available',
  notApplicable: 'Not applicable',
  columns: {
    check: 'Check',
    value: 'Value',
    limit: 'Effective limit',
    margin: 'Margin',
    worstTime: 'Worst time',
    worstFailure: 'Worst credible failure',
    source: 'Source',
    result: 'Result',
  },
};
