import { useCallback, useEffect, useRef, useState } from 'react';
import type { FormEvent } from 'react';
import { askWorkspaceCase } from '../api';
import type { WorkspaceAssistantAnswer, WorkspaceAssistantTurn } from '../api';
import './DemoAssistantCard.css';

const FIRST_QUESTION = 'Explain this modeled result and its limits to a teammate.';

type Exchange = { question: string; answer: WorkspaceAssistantAnswer };

function DemoAssistantCard({ operatorCase }: { operatorCase: unknown }) {
  const [exchanges, setExchanges] = useState<Exchange[]>([]);
  const [question, setQuestion] = useState('');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const pending = useRef<AbortController | null>(null);
  const lastAttempt = useRef<{ question: string; history: WorkspaceAssistantTurn[] }>({ question: FIRST_QUESTION, history: [] });

  const ask = useCallback(async (text: string, history: WorkspaceAssistantTurn[], controller: AbortController) => {
    lastAttempt.current = { question: text, history };
    pending.current?.abort();
    pending.current = controller;
    setLoading(true);
    setError(null);
    try {
      const answer = await askWorkspaceCase(operatorCase, text, history, controller.signal);
      if (controller.signal.aborted) return;
      setExchanges((previous) => [...previous, { question: text, answer }]);
    } catch (cause) {
      if (controller.signal.aborted) return;
      setError(cause instanceof Error ? cause.message : 'Azure OpenAI did not respond.');
    } finally {
      if (!controller.signal.aborted) setLoading(false);
    }
  }, [operatorCase]);

  useEffect(() => {
    const controller = new AbortController();
    // The timer avoids a duplicate Azure request from React StrictMode's
    // mount/cleanup check in development.
    const timer = window.setTimeout(() => void ask(FIRST_QUESTION, [], controller), 0);
    return () => {
      window.clearTimeout(timer);
      controller.abort();
    };
  }, [ask]);

  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const text = question.trim();
    if (!text || loading) return;
    setQuestion('');
    void ask(text, exchanges.slice(-6).map(({ question: asked, answer }) => ({ question: asked, reply: answer.reply })), new AbortController());
  }

  return (
    <section className="card demo-assistant" aria-label="Azure OpenAI case assistant">
      <h3 className="card-kicker">Azure OpenAI case assistant</h3>
      <p className="demo-assistant-note">Your question and the synthetic case result go to team Azure OpenAI. Its answer cannot change the modeled candidate or safety checks.</p>
      {exchanges.map(({ question: asked, answer }, index) => (
        <div className="demo-assistant-exchange" key={index}>
          <p className="field-label">{asked}</p>
          <p>{answer.reply}</p>
          <p className="demo-assistant-model">Generated by Azure OpenAI · {answer.model}</p>
        </div>
      ))}
      {loading && <p role="status">Asking Azure OpenAI…</p>}
      {error && (
        <div role="status">
          <p>Azure OpenAI explanation unavailable: {error}</p>
          <button type="button" className="button-secondary" onClick={() => void ask(lastAttempt.current.question, lastAttempt.current.history, new AbortController())}>Try again</button>
        </div>
      )}
      <form className="demo-assistant-form" onSubmit={submit}>
        <label htmlFor="demo-assistant-question">Ask about this result</label>
        <div>
          <input
            id="demo-assistant-question"
            className="input"
            value={question}
            onChange={(event) => setQuestion(event.target.value)}
            maxLength={1000}
            placeholder="Why is this only a modeled candidate?"
          />
          <button type="submit" className="button-secondary" disabled={!question.trim() || loading}>Ask</button>
        </div>
      </form>
    </section>
  );
}

export default DemoAssistantCard;
