"""Draw the chat assistant's LangGraph.

Usage (with the venv active, from anywhere in the repo):
    graph              # print the graph in the terminal
    graph --view       # open an interactive diagram in your browser
    graph --md         # write docs/chat_graph.md (Mermaid, renders on GitHub)
    graph --png        # write docs/chat_graph.png (needs internet)

Equivalent without the shortcut: python -m scripts.draw_chat_graph [flags]

No Azure credentials are needed: the graph is built with a placeholder model.
"""
from __future__ import annotations

import argparse
import subprocess
import sys
import webbrowser
from pathlib import Path

from langchain_core.language_models import BaseChatModel
from langchain_core.messages import AIMessage
from langchain_core.outputs import ChatGeneration, ChatResult

from backend.app.chat.graph import build_graph
from backend.app.chat.tools import FORECAST_TOOLS

DOCS = Path(__file__).resolve().parents[1] / "docs"


class _PlaceholderModel(BaseChatModel):
    @property
    def _llm_type(self) -> str:
        return "placeholder"

    def bind_tools(self, tools, **kwargs):
        return self

    def _generate(self, messages, stop=None, run_manager=None, **kwargs):
        return ChatResult(generations=[ChatGeneration(message=AIMessage(""))])


def _print_terminal(drawable) -> None:
    try:
        print(drawable.draw_ascii())
        return
    except ImportError:  # grandalf not installed; fall back to an edge list
        pass
    print("Chat assistant graph (pip install grandalf for a box drawing)\n")
    for edge in drawable.edges:
        arrow = "-.->" if edge.conditional else "--->"
        print(f"  {edge.source:>10} {arrow} {edge.target}")
    print("\n  -.-> = conditional (agent decides: call tools or finish)")


def _write_html(mermaid: str) -> Path:
    path = DOCS / "chat_graph.html"
    body = mermaid.split("---", 2)[-1].strip()  # drop the front-matter block
    path.write_text(f"""<!doctype html>
<html><head><meta charset="utf-8"><title>Chat assistant graph</title>
<style>body{{font-family:system-ui,sans-serif;margin:40px;color:#0b0c0c}}</style></head>
<body><h1>Chat assistant graph</h1>
<pre class="mermaid">
{body}
</pre>
<script type="module">
import mermaid from "https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.esm.min.mjs";
mermaid.initialize({{ startOnLoad: true }});
</script></body></html>
""")
    return path


def _open(path: Path) -> None:
    if sys.platform == "darwin":
        subprocess.run(["open", str(path)], check=False)
    else:
        webbrowser.open(path.as_uri())


def main() -> None:
    parser = argparse.ArgumentParser(prog="graph", description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--view", action="store_true", help="open the diagram in your browser")
    parser.add_argument("--md", action="store_true", help="write docs/chat_graph.md")
    parser.add_argument("--png", action="store_true", help="write docs/chat_graph.png via mermaid.ink (needs internet)")
    args = parser.parse_args()

    drawable = build_graph(_PlaceholderModel(), FORECAST_TOOLS).get_graph()
    mermaid = drawable.draw_mermaid()
    DOCS.mkdir(exist_ok=True)

    if not (args.view or args.md or args.png):
        _print_terminal(drawable)

    if args.md:
        tools = "\n".join(f"- `{t.name}`: {t.description.strip().splitlines()[0]}" for t in FORECAST_TOOLS)
        md_path = DOCS / "chat_graph.md"
        md_path.write_text(
            "# Chat assistant graph\n\n"
            "Generated by `graph --md`. Do not edit by hand.\n\n"
            f"```mermaid\n{mermaid}```\n\n"
            f"## Tool nodes\n\n{tools}\n"
        )
        print(f"Wrote {md_path}")

    if args.png:
        png_path = DOCS / "chat_graph.png"
        png_path.write_bytes(drawable.draw_mermaid_png())
        print(f"Wrote {png_path}")

    if args.view:
        html_path = _write_html(mermaid)
        print(f"Opening {html_path}")
        _open(html_path)


if __name__ == "__main__":
    main()
